export const rent = {
    listing1: {
      web_reference: '001',
      price: 'R1 000 000',
      city: 'Durban',
      suburb: 'Chatsworth',
      title: 'New property listing',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      type: 'rent',
      erf_size: '100sqm',
      floor_size: '60sqm',
      levies: 'R200',
      rates_and_taxes: 'R200',
      listing_date: '1 May 2017',
      bedrooms: 3,
      bathrooms: 2,
      kitchen: 1,
      lounge: 1,
      dining_room: 1,
      garage: 1,
      garden: 1,
      pool: 1,
      outbuilding: 1,
      mainimg: 'http://res.cloudinary.com/dhntjibto/image/upload/v1495398402/sale1_n7ei14.jpg',
      property_images: '',
      agents_name: 'Sanjay Math',
      agents_number: '0000000000',
      agents_email: 'homespecialistinfo@gmail.com'
    },
    listing2: {
      web_reference: '002',
      price: 'R1 000 000',
      city: 'Durban',
      suburb: 'Chatsworth',
      title: 'New property listing',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      type: 'rent',
      erf_size: '100sqm',
      floor_size: '60sqm',
      levies: 'R200',
      rates_and_taxes: 'R200',
      listing_date: '1 May 2017',
      bedrooms: 3,
      bathrooms: 2,
      kitchen: 1,
      lounge: 1,
      dining_room: 1,
      garage: 1,
      garden: 1,
      pool: 1,
      outbuilding: 1,
      mainimg: 'http://res.cloudinary.com/dhntjibto/image/upload/v1495398402/sale1_n7ei14.jpg',
      property_images: '',
      agents_name: 'Sanjay Math',
      agents_number: '0000000000',
      agents_email: 'homespecialistinfo@gmail.com'
    },
    listing3: {
      web_reference: '003',
      price: 'R1 000 000',
      city: 'Durban',
      suburb: 'Chatsworth',
      title: 'New property listing',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      type: 'rent',
      erf_size: '100sqm',
      floor_size: '60sqm',
      levies: 'R200',
      rates_and_taxes: 'R200',
      listing_date: '1 May 2017',
      bedrooms: 3,
      bathrooms: 2,
      kitchen: 1,
      lounge: 1,
      dining_room: 1,
      garage: 1,
      garden: 1,
      pool: 1,
      outbuilding: 1,
      mainimg: 'http://res.cloudinary.com/dhntjibto/image/upload/v1495398402/sale1_n7ei14.jpg',
      property_images: '',
      agents_name: 'Sanjay Math',
      agents_number: '0000000000',
      agents_email: 'homespecialistinfo@gmail.com'
    }
}
export const sale = {
    listing1: {
      web_reference: '004',
      price: 'R1 000 000',
      city: 'Durban',
      suburb: 'Chatsworth',
      title: 'New property listing',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      type: 'sale',
      erf_size: '100sqm',
      floor_size: '60sqm',
      levies: 'R200',
      rates_and_taxes: 'R200',
      listing_date: '1 May 2017',
      bedrooms: 3,
      bathrooms: 2,
      kitchen: 1,
      lounge: 1,
      dining_room: 1,
      garage: 1,
      garden: 1,
      pool: 1,
      outbuilding: 1,
      mainimg: 'http://res.cloudinary.com/dhntjibto/image/upload/v1495398402/sale1_n7ei14.jpg',
      property_images: '',
      agents_name: 'Sanjay Math',
      agents_number: '0000000000',
      agents_email: 'homespecialistinfo@gmail.com'
    },
    listing2: {
      web_reference: '005',
      price: 'R1 000 000',
      city: 'Durban',
      suburb: 'Chatsworth',
      title: 'New property listing',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      type: 'sale',
      erf_size: '100sqm',
      floor_size: '60sqm',
      levies: 'R200',
      rates_and_taxes: 'R200',
      listing_date: '1 May 2017',
      bedrooms: 3,
      bathrooms: 2,
      kitchen: 1,
      lounge: 1,
      dining_room: 1,
      garage: 1,
      garden: 1,
      pool: 1,
      outbuilding: 1,
      mainimg: 'http://res.cloudinary.com/dhntjibto/image/upload/v1495398402/sale1_n7ei14.jpg',
      property_images: '',
      agents_name: 'Sanjay Math',
      agents_number: '0000000000',
      agents_email: 'homespecialistinfo@gmail.com'
    },
    listing3: {
      web_reference: '006',
      price: 'R1 000 000',
      city: 'Durban',
      suburb: 'Chatsworth',
      title: 'New property listing',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      type: 'sale',
      erf_size: '100sqm',
      floor_size: '60sqm',
      levies: 'R200',
      rates_and_taxes: 'R200',
      listing_date: '1 May 2017',
      bedrooms: 3,
      bathrooms: 2,
      kitchen: 1,
      lounge: 1,
      dining_room: 1,
      garage: 1,
      garden: 1,
      pool: 1,
      outbuilding: 1,
      mainimg: 'http://res.cloudinary.com/dhntjibto/image/upload/v1495398402/sale1_n7ei14.jpg',
      property_images: '',
      agents_name: 'Sanjay Math',
      agents_number: '0000000000',
      agents_email: 'homespecialistinfo@gmail.com'
    }
}